version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run: python countdown_timer.py

      # Run the test cases
      - run:
          name: Run test cases
          command: python -m unittest.py


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
      # - test:
          # requires:
          #   - build
