version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run: python countdown_timer.py
      
    test:
      docker:
        - image: cimg/python:3.11

      steps:
        - checkout
        - run: python unittest.py

      # - run:
      #     name: Run tests
      #     command: pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
    
      - test:
          requires:
            - build
