name: Dependabot
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Dependabot
        uses: dependabot/dependabot-github-actions@v2.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          package_manager: "all"
